// =============================================================================
// SEED DATA - Generated from actual inventory CSV
// =============================================================================

import { createInventoryItem, createVisit } from './db.js';

// Store ID mappings for CSV data
const STORE_MAPPING = {
  'Value Village Boutique_Downtown Granville': 'vv_boutique_downtown',
  'Value Village_Queensborough': 'vv_queensborough',
  'MCC Center Thrift Shop_Abbotsford': 'mcc_abbotsford_centre',
  'Private Sale - Leslie_Edmonton': 'private_sale_leslie',
  'Salvation Army_Edmonton': 'sa_edmonton',
  'Salvation Army_Coquitlam': 'sa_coquitlam',
  'RCH Auxiliary Thrift Store_': 'rch_auxiliary',
  'St Barnabas Thrift Store_': 'st_barnabas',
  'RAPS Thrift Store_Granville Avenue': 'raps_granville',
  'Steveston Treasure Cottage_': 'steveston_treasure',
  'Richmond Hospital Healthcare Auxiliary Thrift Shop_': 'richmond_hospital_aux',
  'Value Village_Granville Avenue': 'vv_richmond'
};

// Actual inventory from CSV
const INVENTORY_ITEMS = [
  {
    title: 'Jonathan Simkhai Mustard yellow sweater',
    category: 'clothing',
    subcategory: 'sweater',
    brand: 'Jonathan Simkhai',
    store_id: 'vv_boutique_downtown',
    acquisition_date: '2025-11-17',
    purchase_price: 7.49,
    labeled_size: 'M',
    primary_material: '100% cashmere',
    status: 'unlisted',
    description: 'Mustard yellow sweater. Recommended shipping: Poly mailer'
  },
  {
    title: 'Lord & Taylor Black turtleneck sweater',
    category: 'clothing',
    subcategory: 'sweater',
    brand: 'Lord & Taylor',
    store_id: 'vv_boutique_downtown',
    acquisition_date: '2025-11-17',
    purchase_price: 10.00,
    labeled_size: 'XXL',
    primary_material: 'Cashmere',
    condition_notes: 'Approximate price. Made in Bangladesh.',
    status: 'unlisted',
    description: 'Black turtleneck sweater. Recommended shipping: Poly mailer (large)'
  },
  {
    title: 'Ellen Tracy Aubergine sweater with button collar detail',
    category: 'clothing',
    subcategory: 'sweater',
    brand: 'Ellen Tracy',
    store_id: 'vv_boutique_downtown',
    acquisition_date: '2025-11-17',
    purchase_price: 10.00,
    labeled_size: 'L',
    primary_material: '100% Merino wool',
    condition_notes: 'Approximate price. Made in Cambodia.',
    status: 'unlisted',
    description: 'Aubergine sweater with button collar detail. Recommended shipping: Poly mailer'
  },
  {
    title: 'Renee Tener for Jeanne Pierre Magenta cardigan',
    category: 'clothing',
    subcategory: 'sweater',
    brand: 'Renee Tener for Jeanne Pierre',
    store_id: 'vv_boutique_downtown',
    acquisition_date: '2025-11-17',
    purchase_price: 10.00,
    labeled_size: 'L',
    primary_material: "Lamb's wool",
    condition_notes: 'Approximate price. Made in Hong Kong.',
    status: 'unlisted',
    description: 'Magenta cardigan. Recommended shipping: Poly mailer'
  },
  {
    title: 'Anne Klein 2 Cream collarless blazer',
    category: 'clothing',
    subcategory: 'jacket',
    brand: 'Anne Klein 2',
    store_id: 'vv_queensborough',
    acquisition_date: '2025-12-18',
    purchase_price: 12.00,
    labeled_size: '8',
    primary_material: '100% silk',
    status: 'unlisted',
    description: 'Cream collarless blazer. Recommended shipping: Poly mailer'
  },
  {
    title: 'Aquascutum Cream wool blazer',
    category: 'clothing',
    subcategory: 'jacket',
    brand: 'Aquascutum',
    store_id: 'vv_queensborough',
    acquisition_date: '2025-12-18',
    purchase_price: 20.00,
    labeled_size: 'Unspecified',
    primary_material: 'Wool',
    status: 'unlisted',
    description: 'Cream wool blazer. Recommended shipping: Poly mailer'
  },
  {
    title: 'Holt Renfrew Black velvet jacket with satin seam bindings and toggle closures',
    category: 'clothing',
    subcategory: 'jacket',
    brand: 'Holt Renfrew',
    store_id: 'vv_queensborough',
    acquisition_date: '2025-12-18',
    purchase_price: 10.00,
    labeled_size: 'M',
    primary_material: 'Velvet',
    status: 'unlisted',
    description: 'Black velvet jacket with satin seam bindings and toggle closures. Recommended shipping: 12" x 10" x 4" box'
  },
  {
    title: 'The Alpaca Experience by Du Store Alpaca Aubergine ribbed cardigan',
    category: 'clothing',
    subcategory: 'sweater',
    brand: 'The Alpaca Experience by Du Store Alpaca',
    store_id: 'mcc_abbotsford_centre',
    acquisition_date: '2025-12-20',
    purchase_price: 4.50,
    labeled_size: 'XS',
    primary_material: '100% alpaca',
    status: 'unlisted',
    description: 'Aubergine ribbed cardigan. Recommended shipping: Poly mailer'
  },
  {
    title: 'Jones New York Separates Aubergine ribbed turtleneck',
    category: 'clothing',
    subcategory: 'sweater',
    brand: 'Jones New York Separates',
    store_id: 'mcc_abbotsford_centre',
    acquisition_date: '2025-12-20',
    purchase_price: 12.00,
    primary_material: '100% Merino wool',
    condition_notes: 'Made in China.',
    status: 'unlisted',
    description: 'Aubergine ribbed turtleneck. Recommended shipping: Poly mailer'
  },
  {
    title: 'Noelle Rouine Paris Peur Spécifique Burgundy sweater',
    category: 'clothing',
    subcategory: 'sweater',
    brand: 'Noelle Rouine Paris',
    store_id: 'private_sale_leslie',
    acquisition_date: '2025-12-26',
    purchase_price: 5.00,
    primary_material: '20% cashmere/80% wool',
    condition_notes: 'Approximate price. Made in Hong Kong.',
    status: 'unlisted',
    description: 'Peur Spécifique sweater in burgundy. Recommended shipping: Poly mailer'
  },
  {
    title: 'Russ Signature Wool cardigan',
    category: 'clothing',
    subcategory: 'sweater',
    brand: 'Russ Signature',
    store_id: 'private_sale_leslie',
    acquisition_date: '2025-12-26',
    purchase_price: 5.00,
    labeled_size: '2X',
    primary_material: 'Wool',
    condition_notes: 'Approximate price; possibly felted/shrunken. Made in Hong Kong.',
    status: 'unlisted',
    description: 'Wool cardigan. Recommended shipping: Poly mailer (large)'
  },
  {
    title: 'Ellen Tracy Aubergine sweater with button collar detail',
    category: 'clothing',
    subcategory: 'sweater',
    brand: 'Ellen Tracy',
    store_id: 'private_sale_leslie',
    acquisition_date: '2025-12-26',
    purchase_price: 10.00,
    labeled_size: 'L',
    primary_material: '100% Merino wool',
    condition_notes: 'Approximate price. Made in Cambodia.',
    status: 'unlisted',
    description: 'Aubergine sweater with button collar detail. Recommended shipping: Poly mailer'
  },
  {
    title: 'Melanie Lyne Bright red coat with black buttons',
    category: 'clothing',
    subcategory: 'jacket',
    brand: 'Melanie Lyne',
    store_id: 'sa_edmonton',
    acquisition_date: '2025-12-27',
    purchase_price: 20.00,
    labeled_size: '16',
    primary_material: 'Wool/cashmere',
    condition_notes: 'Approximate date',
    status: 'unlisted',
    description: 'Bright red coat with black buttons. Recommended shipping: 16" x 12" x 4" box'
  },
  {
    title: 'Danier Red leather blazer',
    category: 'clothing',
    subcategory: 'jacket',
    brand: 'Danier',
    store_id: 'sa_coquitlam',
    acquisition_date: '2026-01-02',
    purchase_price: 20.00,
    labeled_size: 'M',
    primary_material: 'Leather',
    condition_notes: 'Made in Canada.',
    status: 'unlisted',
    description: 'Red leather blazer. Recommended shipping: 14" x 10" x 4" box'
  },
  {
    title: 'Giannini Fashion Collection Tan coat',
    category: 'clothing',
    subcategory: 'jacket',
    brand: 'Giannini Fashion Collection',
    store_id: 'vv_queensborough',
    acquisition_date: '2026-01-08',
    purchase_price: 27.00,
    labeled_size: 'S',
    primary_material: '75% cashmere/25% wool',
    status: 'unlisted',
    description: 'Tan coat. Recommended shipping: 16" x 12" x 4" box'
  },
  {
    title: 'Gloverall Tan overcoat with hood and wooden toggle buttons',
    category: 'clothing',
    subcategory: 'jacket',
    brand: 'Gloverall',
    store_id: 'vv_queensborough',
    acquisition_date: '2026-01-08',
    purchase_price: 21.00,
    labeled_size: 'British 34',
    status: 'unlisted',
    description: 'Tan overcoat with hood and wooden toggle buttons. Recommended shipping: 16" x 14" x 6" box'
  },
  {
    title: 'Pat Perkins Original Cream long overcoat with red/green tartan detail and scarf',
    category: 'clothing',
    subcategory: 'jacket',
    brand: 'Pat Perkins Original',
    store_id: 'vv_queensborough',
    acquisition_date: '2026-01-08',
    purchase_price: 10.49,
    labeled_size: 'S',
    primary_material: 'Wool',
    condition_notes: 'Made in England.',
    status: 'unlisted',
    description: 'Cream long overcoat with red/green tartan detail and scarf. Recommended shipping: 16" x 12" x 4" box'
  },
  {
    title: 'Opera Black leather jacket',
    category: 'clothing',
    subcategory: 'jacket',
    brand: 'Opera',
    store_id: 'vv_queensborough',
    acquisition_date: '2026-01-08',
    purchase_price: 20.00,
    labeled_size: 'Korean 15',
    primary_material: 'Leather',
    condition_notes: 'Made in Korea.',
    status: 'unlisted',
    description: 'Black leather jacket. Recommended shipping: 14" x 10" x 4" box'
  },
  {
    title: 'Lucian Matis Black cocktail dress with beaded collar and cuff detail',
    category: 'clothing',
    subcategory: 'dress',
    brand: 'Lucian Matis',
    store_id: 'vv_queensborough',
    acquisition_date: '2026-01-08',
    purchase_price: 28.00,
    primary_material: 'Poly/rayon',
    status: 'unlisted',
    description: 'Black cocktail dress with beaded collar and cuff detail. Recommended shipping: 12" x 10" x 4" box'
  },
  {
    title: 'Moiselle Aubergine silk dress with polyester sequin detail',
    category: 'clothing',
    subcategory: 'dress',
    brand: 'Moiselle',
    store_id: 'vv_queensborough',
    acquisition_date: '2026-01-08',
    purchase_price: 23.00,
    labeled_size: '38',
    primary_material: 'Silk',
    status: 'unlisted',
    description: 'Aubergine silk dress with polyester sequin detail. Recommended shipping: 12" x 10" x 4" box'
  },
  {
    title: 'Bardot Black lace over nude sleeveless cocktail dress',
    category: 'clothing',
    subcategory: 'dress',
    brand: 'Bardot',
    store_id: 'vv_queensborough',
    acquisition_date: '2026-01-08',
    purchase_price: 20.49,
    labeled_size: 'UK 16',
    primary_material: 'Lace',
    status: 'unlisted',
    description: 'Black lace over nude sleeveless cocktail dress. Recommended shipping: Poly mailer'
  },
  {
    title: 'Aidan Mattox Black lace cocktail dress',
    category: 'clothing',
    subcategory: 'dress',
    brand: 'Aidan Mattox',
    store_id: 'vv_queensborough',
    acquisition_date: '2026-01-08',
    purchase_price: 23.00,
    labeled_size: 'EU 32',
    primary_material: 'Lace',
    status: 'unlisted',
    description: 'Black lace cocktail dress. Recommended shipping: Poly mailer'
  },
  {
    title: 'Eileen Fisher Red oversized sweater',
    category: 'clothing',
    subcategory: 'sweater',
    brand: 'Eileen Fisher',
    store_id: 'vv_queensborough',
    acquisition_date: '2026-01-08',
    purchase_price: 11.79,
    labeled_size: 'XL',
    primary_material: '80% silk/20% cotton',
    status: 'unlisted',
    description: 'Red oversized sweater. Recommended shipping: Poly mailer (large)'
  },
  {
    title: 'Episode by Carolyn Freeman Chocolate brown cardigan',
    category: 'clothing',
    subcategory: 'sweater',
    brand: 'Episode by Carolyn Freeman',
    store_id: 'vv_queensborough',
    acquisition_date: '2026-01-08',
    purchase_price: 16.49,
    labeled_size: 'M',
    primary_material: '70% wool/30% cashmere',
    condition_notes: 'Made in Hong Kong.',
    status: 'unlisted',
    description: 'Chocolate brown cardigan. Recommended shipping: Poly mailer'
  },
  {
    title: 'Fly London Beige pumps',
    category: 'shoes',
    subcategory: 'pumps',
    brand: 'Fly London',
    store_id: 'rch_auxiliary',
    acquisition_date: '2026-01-09',
    purchase_price: 25.00,
    labeled_size: 'EU 38',
    condition_notes: 'Made in Portugal.',
    status: 'unlisted',
    description: 'Beige pumps. Recommended shipping: 12" x 8" x 4" box'
  },
  {
    title: 'Frye Cognac knee-high heeled boots',
    category: 'shoes',
    subcategory: 'boots',
    brand: 'Frye',
    store_id: 'rch_auxiliary',
    acquisition_date: '2026-01-09',
    purchase_price: 37.50,
    labeled_size: '~10',
    primary_material: 'Leather',
    status: 'unlisted',
    description: 'Cognac knee-high heeled boots. Recommended shipping: 16" x 8" x 6" boot box'
  },
  {
    title: 'Ingledews Gray/black wingtip high-cut Oxfords',
    category: 'shoes',
    subcategory: 'oxfords',
    brand: 'Ingledews',
    store_id: 'rch_auxiliary',
    acquisition_date: '2026-01-09',
    purchase_price: 8.00,
    labeled_size: 'EU 39',
    condition_notes: 'Made in Italy.',
    status: 'unlisted',
    description: 'Gray/black wingtip high-cut Oxfords. Recommended shipping: 12" x 8" x 4" box'
  },
  {
    title: 'Ingledews Distressed gunmetal heeled booties',
    category: 'shoes',
    subcategory: 'booties',
    brand: 'Ingledews',
    store_id: 'rch_auxiliary',
    acquisition_date: '2026-01-09',
    purchase_price: 6.00,
    labeled_size: 'EU 39',
    condition_notes: 'Made in Italy.',
    status: 'unlisted',
    description: 'Distressed gunmetal heeled booties. Recommended shipping: 12" x 8" x 4" box'
  },
  {
    title: 'Miz Mooz Zip-up ankle boots with eyelet detail',
    category: 'shoes',
    subcategory: 'boots',
    brand: 'Miz Mooz',
    store_id: 'rch_auxiliary',
    acquisition_date: '2026-01-09',
    purchase_price: 12.00,
    labeled_size: '9',
    status: 'unlisted',
    description: 'Zip-up ankle boots with eyelet detail. Recommended shipping: 12" x 8" x 4" box'
  },
  {
    title: 'Carlo Rosetti Burgundy/purple lace-up Oxford heels',
    category: 'shoes',
    subcategory: 'oxfords',
    brand: 'Carlo Rosetti',
    store_id: 'st_barnabas',
    acquisition_date: '2026-01-10',
    purchase_price: 15.00,
    labeled_size: '6.5',
    condition_notes: 'Made in Mexico.',
    status: 'unlisted',
    description: 'Burgundy/purple lace-up Oxford heels. Recommended shipping: 12" x 8" x 4" box'
  },
  {
    title: 'Think! Oxblood heeled ankle boots with eyelet detail',
    category: 'shoes',
    subcategory: 'boots',
    brand: 'Think!',
    store_id: 'raps_granville',
    acquisition_date: '2026-01-11',
    purchase_price: 4.00,
    labeled_size: '35',
    condition_notes: 'Made in Italy.',
    status: 'unlisted',
    description: 'Oxblood heeled ankle boots with eyelet detail. Recommended shipping: 12" x 8" x 4" box'
  },
  {
    title: 'Wonders Black heeled shooties',
    category: 'shoes',
    subcategory: 'booties',
    brand: 'Wonders',
    store_id: 'raps_granville',
    acquisition_date: '2026-01-11',
    purchase_price: 4.00,
    labeled_size: '40',
    condition_notes: 'Made in Spain.',
    status: 'unlisted',
    description: 'Black heeled shooties. Recommended shipping: 12" x 8" x 4" box'
  },
  {
    title: 'Chie Mihara Black Mary Janes with suede floral detail',
    category: 'shoes',
    subcategory: 'mary_janes',
    brand: 'Chie Mihara',
    store_id: 'raps_granville',
    acquisition_date: '2026-01-11',
    purchase_price: 4.00,
    labeled_size: '38',
    condition_notes: 'Made in Spain.',
    status: 'unlisted',
    description: 'Black Mary Janes with suede floral detail. Recommended shipping: 12" x 8" x 4" box'
  },
  {
    title: 'Marc Aurel Bright spring green bouclé coat',
    category: 'clothing',
    subcategory: 'jacket',
    brand: 'Marc Aurel',
    store_id: 'raps_granville',
    acquisition_date: '2026-01-11',
    purchase_price: 12.00,
    labeled_size: '36',
    primary_material: 'Wool/cotton/angora/silk/linen/viscose blend',
    condition_notes: 'Made in Germany.',
    status: 'unlisted',
    description: 'Bright spring green bouclé coat. Recommended shipping: 16" x 12" x 4" box'
  },
  {
    title: 'Sesto Golf by Sherry Cognac golf shoes with woven detail',
    category: 'shoes',
    subcategory: 'golf_shoes',
    brand: 'Sesto Golf by Sherry',
    store_id: 'steveston_treasure',
    acquisition_date: '2026-01-11',
    purchase_price: 30.00,
    labeled_size: "Men's 9.5",
    primary_material: 'Leather',
    condition_notes: 'Made in Italy.',
    status: 'unlisted',
    description: 'Cognac golf shoes with woven detail. Recommended shipping: 14" x 10" x 5" box'
  },
  {
    title: 'John Fluevog Dalai Black ankle boots with gray laced-up detail',
    category: 'shoes',
    subcategory: 'boots',
    brand: 'John Fluevog',
    store_id: 'steveston_treasure',
    acquisition_date: '2026-01-11',
    purchase_price: 20.00,
    labeled_size: '5',
    primary_material: 'Leather',
    status: 'unlisted',
    description: 'Dalai ankle boots with gray laced-up detail. Recommended shipping: 12" x 8" x 4" box'
  },
  {
    title: 'Danier Black leather jacket with gray zippers and lining',
    category: 'clothing',
    subcategory: 'jacket',
    brand: 'Danier',
    store_id: 'richmond_hospital_aux',
    acquisition_date: '2026-01-11',
    purchase_price: 12.00,
    labeled_size: 'XS',
    primary_material: 'Leather',
    status: 'unlisted',
    description: 'Black leather jacket with gray zippers and lining. Recommended shipping: 14" x 10" x 4" box'
  },
  {
    title: 'Black riding boots',
    category: 'shoes',
    subcategory: 'boots',
    brand: null,
    store_id: 'richmond_hospital_aux',
    acquisition_date: '2026-01-11',
    purchase_price: 12.00,
    labeled_size: '37',
    primary_material: 'Leather',
    condition_notes: 'Made in Italy.',
    status: 'unlisted',
    description: 'Black riding boots. Recommended shipping: 16" x 8" x 6" boot box'
  },
  {
    title: 'Evan Picone Black pumps with square toe',
    category: 'shoes',
    subcategory: 'pumps',
    brand: 'Evan Picone',
    store_id: 'richmond_hospital_aux',
    acquisition_date: '2026-01-11',
    purchase_price: 6.00,
    labeled_size: '7.5 narrow',
    condition_notes: 'Made in Spain.',
    status: 'unlisted',
    description: 'Black pumps with square toe. Recommended shipping: 12" x 8" x 4" box'
  },
  {
    title: 'Fera Giacomo Black pumps with triple Mary Jane strap detail',
    category: 'shoes',
    subcategory: 'pumps',
    brand: 'Fera Giacomo',
    store_id: 'richmond_hospital_aux',
    acquisition_date: '2026-01-11',
    purchase_price: 18.00,
    labeled_size: '38',
    condition_notes: 'Made in Italy.',
    status: 'unlisted',
    description: 'Black pumps with triple Mary Jane strap detail. Recommended shipping: 12" x 8" x 4" box'
  },
  {
    title: 'Roots Tuff Black ankle boots',
    category: 'shoes',
    subcategory: 'boots',
    brand: 'Roots',
    store_id: 'vv_richmond',
    acquisition_date: '2026-01-11',
    purchase_price: 35.00,
    labeled_size: '6.5',
    status: 'unlisted',
    description: 'Tuff ankle boots. Recommended shipping: 12" x 8" x 4" box'
  },
  {
    title: 'Babaton The Connor Camel coat',
    category: 'clothing',
    subcategory: 'jacket',
    brand: 'Babaton',
    store_id: 'vv_richmond',
    acquisition_date: '2026-01-11',
    purchase_price: 38.49,
    labeled_size: 'S',
    primary_material: '100% Italian wool',
    status: 'unlisted',
    description: 'The Connor coat in camel. Recommended shipping: 16" x 12" x 4" box'
  },
  {
    title: 'Escada by Margaretha Ley Red blazer with black buttons',
    category: 'clothing',
    subcategory: 'jacket',
    brand: 'Escada by Margaretha Ley',
    store_id: 'vv_richmond',
    acquisition_date: '2026-01-11',
    purchase_price: 18.00,
    labeled_size: '40',
    primary_material: '100% cashmere',
    condition_notes: 'Made in Germany.',
    status: 'unlisted',
    description: 'Red blazer with black buttons. Recommended shipping: 14" x 10" x 4" box'
  },
  {
    title: 'Escada by Margaretha Ley Aubergine blazer with black velvet collar and epaulette details',
    category: 'clothing',
    subcategory: 'jacket',
    brand: 'Escada by Margaretha Ley',
    store_id: 'vv_richmond',
    acquisition_date: '2026-01-11',
    purchase_price: 18.00,
    labeled_size: '38',
    primary_material: '98% wool/2% elastane',
    condition_notes: 'Made in Germany.',
    status: 'unlisted',
    description: 'Aubergine blazer with black velvet collar and epaulette details. Recommended shipping: 14" x 10" x 4" box'
  },
  {
    title: 'Nanette Lepore Olive green wool frock coat',
    category: 'clothing',
    subcategory: 'jacket',
    brand: 'Nanette Lepore',
    store_id: 'vv_richmond',
    acquisition_date: '2026-01-11',
    purchase_price: 45.00,
    labeled_size: '10',
    primary_material: 'Wool',
    condition_notes: 'NWT',
    status: 'unlisted',
    description: 'Olive green wool frock coat. New with tags. Recommended shipping: 16" x 12" x 4" box'
  },
  {
    title: 'UB Leather Collection Cream wool coat',
    category: 'clothing',
    subcategory: 'jacket',
    brand: 'UB Leather Collection',
    store_id: 'vv_richmond',
    acquisition_date: '2026-01-11',
    purchase_price: 35.00,
    labeled_size: 'S',
    primary_material: 'Wool',
    condition_notes: 'Made in China.',
    status: 'unlisted',
    description: 'Cream wool coat. Recommended shipping: 16" x 12" x 4" box'
  },
  {
    title: 'Highland Queen Pure wool blazer',
    category: 'clothing',
    subcategory: 'jacket',
    brand: 'Highland Queen',
    store_id: 'vv_richmond',
    acquisition_date: '2026-01-11',
    purchase_price: 15.00,
    labeled_size: 'M',
    primary_material: 'Wool',
    condition_notes: 'Made in Canada.',
    status: 'unlisted',
    description: 'Pure wool blazer. Recommended shipping: Poly mailer'
  }
];

export async function seedDatabase() {
  console.log('Seeding database with actual inventory...');

  let itemCount = 0;

  for (const item of INVENTORY_ITEMS) {
    try {
      await createInventoryItem(item);
      itemCount++;
      console.log(`Created item: ${item.title}`);
    } catch (err) {
      console.error(`Failed to create item: ${item.title}`, err);
    }
  }

  console.log(`Seeding complete: ${itemCount} items`);
  return { itemCount, visitCount: 0 };
}

// Manual seeding only - call seedDatabase() from console or UI button
